-- 项目收尾：增加主体隔离的聊天会话目录和脱敏消息历史。
-- PostgreSQL 不保存联系方式明文、Token、Prompt、思维链、工具原始结果或
-- 内部服务地址；Redis 过期时只使用受控快照和少量最近消息恢复工作记忆。

BEGIN;

CREATE TABLE IF NOT EXISTS chat_conversations (
    id VARCHAR(64) PRIMARY KEY,
    tenant_id VARCHAR(128) NOT NULL,
    owner_user_id VARCHAR(64) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    owner_role VARCHAR(32) NOT NULL,
    title VARCHAR(80) NOT NULL DEFAULT '新会话',
    title_is_custom BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(16) NOT NULL DEFAULT 'active',
    context_snapshot JSON NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_message_at TIMESTAMP,
    CONSTRAINT ck_chat_conversation_owner_role
        CHECK (owner_role IN ('parent', 'teacher')),
    CONSTRAINT ck_chat_conversation_status CHECK (status IN ('active'))
);

CREATE INDEX IF NOT EXISTS ix_chat_conversation_owner_recent
    ON chat_conversations(
        tenant_id, owner_user_id, owner_role, last_message_at DESC
    );

CREATE TABLE IF NOT EXISTS chat_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id VARCHAR(64) NOT NULL
        REFERENCES chat_conversations(id) ON DELETE CASCADE,
    sequence_no INTEGER NOT NULL,
    role VARCHAR(16) NOT NULL,
    content TEXT NOT NULL,
    message_type VARCHAR(16) NOT NULL DEFAULT 'text',
    safe_metadata JSON NOT NULL DEFAULT '{}',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_chat_message_conversation_sequence
        UNIQUE (conversation_id, sequence_no),
    CONSTRAINT ck_chat_message_role CHECK (role IN ('user', 'assistant')),
    CONSTRAINT ck_chat_message_type CHECK (message_type IN ('text'))
);

CREATE INDEX IF NOT EXISTS ix_chat_message_conversation_sequence
    ON chat_messages(conversation_id, sequence_no);

COMMIT;
